"""add rating and color label to staged files

Revision ID: 278b43ae8e54
Revises: aa093e250449
Create Date: 2026-07-08 19:57:20.456260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278b43ae8e54'
down_revision: Union[str, None] = 'aa093e250449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this is safe even if a staging session already has
    # rows (SQLite requires a default when adding a NOT NULL column to a
    # non-empty table).
    op.add_column(
        'import_staged_files', sa.Column('rating', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'import_staged_files',
        sa.Column(
            'color_label',
            sa.Enum('none', 'red', 'orange', 'yellow', 'green', 'blue', 'magenta', 'gray', name='colorlabel'),
            nullable=False,
            server_default='none',
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_staged_files', 'color_label')
    op.drop_column('import_staged_files', 'rating')
    # ### end Alembic commands ###
