"""initial schema

Revision ID: 55be4bd74c10
Revises: 
Create Date: 2026-07-08 18:12:15.668645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55be4bd74c10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('albums',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent_album_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_owner_id'), 'albums', ['owner_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('perceptual_hash', sa.String(), nullable=True),
    sa.Column('file_type', sa.Enum('jpeg', 'png', 'raw', name='filetype'), nullable=False),
    sa.Column('raw_format', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camera_make', sa.String(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.String(), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('color_label', sa.Enum('none', 'red', 'orange', 'yellow', 'green', 'blue', 'magenta', 'gray', name='colorlabel'), nullable=False),
    sa.Column('paired_image_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paired_image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_images_file_hash'), 'images', ['file_hash'], unique=False)
    op.create_index(op.f('ix_images_file_type'), 'images', ['file_type'], unique=False)
    op.create_index(op.f('ix_images_owner_id'), 'images', ['owner_id'], unique=False)
    op.create_index(op.f('ix_images_perceptual_hash'), 'images', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_images_taken_at'), 'images', ['taken_at'], unique=False)
    op.create_table('import_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('staging', 'committed', 'discarded', name='importsessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_sessions_owner_id'), 'import_sessions', ['owner_id'], unique=False)
    op.create_table('album_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'image_id')
    )
    op.create_index(op.f('ix_album_images_album_id'), 'album_images', ['album_id'], unique=False)
    op.create_index(op.f('ix_album_images_image_id'), 'album_images', ['image_id'], unique=False)
    op.create_table('import_staged_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('import_session_id', sa.String(), nullable=False),
    sa.Column('staged_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('jpeg', 'png', 'raw', name='filetype'), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('perceptual_hash', sa.String(), nullable=True),
    sa.Column('exif_json', sa.String(), nullable=True),
    sa.Column('duplicate_of_image_id', sa.String(), nullable=True),
    sa.Column('is_near_duplicate', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['import_session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_staged_files_import_session_id'), 'import_staged_files', ['import_session_id'], unique=False)
    op.create_index(op.f('ix_import_staged_files_sha256'), 'import_staged_files', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_staged_files_sha256'), table_name='import_staged_files')
    op.drop_index(op.f('ix_import_staged_files_import_session_id'), table_name='import_staged_files')
    op.drop_table('import_staged_files')
    op.drop_index(op.f('ix_album_images_image_id'), table_name='album_images')
    op.drop_index(op.f('ix_album_images_album_id'), table_name='album_images')
    op.drop_table('album_images')
    op.drop_index(op.f('ix_import_sessions_owner_id'), table_name='import_sessions')
    op.drop_table('import_sessions')
    op.drop_index(op.f('ix_images_taken_at'), table_name='images')
    op.drop_index(op.f('ix_images_perceptual_hash'), table_name='images')
    op.drop_index(op.f('ix_images_owner_id'), table_name='images')
    op.drop_index(op.f('ix_images_file_type'), table_name='images')
    op.drop_index(op.f('ix_images_file_hash'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_albums_owner_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_table('users')
    # ### end Alembic commands ###
