"""add manual rotation and crop to images

Revision ID: c4794094b725
Revises: 278b43ae8e54
Create Date: 2026-07-08 20:24:28.245590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4794094b725'
down_revision: Union[str, None] = '278b43ae8e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this is safe against a non-empty images table (this
    # runs against real libraries that may already have committed photos).
    op.add_column('images', sa.Column('edit_rotation', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('images', sa.Column('edit_crop_x', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('edit_crop_y', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('edit_crop_width', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('edit_crop_height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'edit_crop_height')
    op.drop_column('images', 'edit_crop_width')
    op.drop_column('images', 'edit_crop_y')
    op.drop_column('images', 'edit_crop_x')
    op.drop_column('images', 'edit_rotation')
    # ### end Alembic commands ###
